### ISSUE TITLE
2.1.54 issue when highlighting multiple cards

### ISSUE THREAD

**Issue by talkael** [AnKing-Memberships/high-yield-tags#14]
The addon doesnt work when you highlight multiple cards but works only one at a time in 2.1.54

**Comment by AmrAliDawoud** [comment]
Me too, did u find any solution?

**Comment by InvisibleDeck** [comment]
Also running into this same issue.

**Comment by hssnnkim** [comment]
Yes we would really appreciate an update to be compatible with 2.1.54, this add-on is so important to how I organize my study plan to match my class lectures.

**Comment by Kona61** [comment]
Hey guys. I have a somewhat modified version of the add-on that I tailored for myself so it may not be ideal for everyone else. However, I am not very good at coding so I take no responsibility if this somehow managed to break something in a way I don't understand.
[High Yield Tags Modified.zip](https://github.com/Arthur-Milchior/anki-number-of-selected-tags/files/9558189/High.Yield.Tags.Modified.zip)

**Comment by AmrAliDawoud** [comment]
@Kona61 Thank you very much, could you apply a Qt5 version?
Also, you fixed the highlight color ot DarkCyan. I fixed both on my version and it works perfectly till now, but this is your effort, so I don't think I should upload these small fixes.

**Comment by akavi1** [comment]
@Kona61 Thanks for this, it working for me on 2.1.54. What edits did you make? How is it different from the original?

**Comment by AmrAliDawoud** [comment]
[High.Yield.Tags.Modified Anki 2.1.54 Qt5.zip](https://github.com/Arthur-Milchior/anki-number-of-selected-tags/files/9594039/High.Yield.Tags.Modified.Anki.2.1.54.Qt5.zip)

I modified it to work with Qt5 and made changing the highlight color possible because it was fixed to dark cyan

**Comment by talkael** [comment]
How are you uploading the add-on to anki? When I unzip the file its not giving me a ".ankiaddon" format?

**Comment by AnKingMed** [comment]
@DoctorToBeIn23 you can test this with the new version and close this issue if it's fixed

**Comment by DoctorToBeIn23** [comment]
> @DoctorToBeIn23 you can test this with the new version and close this issue if it's fixed

The add on was recently updated and does work for 2.1.54+.
