### ISSUE TITLE
Expected time-delay after pressing shortcut?

### ISSUE THREAD

**Issue by kenf1** [AnKing-Memberships/high-yield-tags#16]
What is expected wait-time for popup (see below) to appear after pressing keyboard shortcut?

![](https://github.com/AnKingMed/high-yield-tags/blob/master/img2.png?raw=true)

Installed on Anki v 2.1.54 (b6a7760c)⁩ but unable to get popup to appear. Tried both `Cmd + T, V` and `Ctrl + T, V` after clicking on a tag.

**Comment by DoctorToBeIn23** [comment]
I am able to open the entire AnKing v12 deck in seconds. You need to be sure you are updated to the newest version of the add on.
