### ISSUE TITLE
Escape and or cancel button dont work

### ISSUE THREAD

**Issue by DoctorToBeIn23** [AnKing-Memberships/high-yield-tags#5]
When you press cancel it just toggels to the next phase of the add on

**Comment by Arthur-Milchior** [comment]
When you press cancel where ? Please make more detailled bug report. I don't even use this add-on, I've got no context here

**Comment by DoctorToBeIn23** [comment]
As soon as you trigger the shortcut and are able to type in what to get highlighted or what value to box. The cancel button doesn’t terminate the shortcut.

**Comment by Arthur-Milchior** [comment]
Thank you, I get it now

**Comment by Arthur-Milchior** [comment]
Please update

**Comment by Arthur-Milchior** [comment]
The correction literally took me less than 2 minutes.
![2020-05-01-195028_732x233_scrot](https://user-images.githubusercontent.com/357361/80828115-096afe80-8be5-11ea-8af1-74ad5acd6a4e.png)

**Comment by DoctorToBeIn23** [comment]
Hahah awesome, works great!!!
